name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install opencv-python-headless jupyter nbconvert matplotlib numpy scikit-learn scipy wandb==0.12.21

      - name: Run file verification script
        run: python action_file.py

      - name: Execute Jupyter Notebook
        run: jupyter nbconvert --to notebook --execute "Lab 5-Spring 2025 (1).ipynb" --output "Lab 5-Spring 2025 (1)_executed.ipynb"
